version: '3.4'

services:

  rabbitmqpcf.web:
    image: ${DOCKER_REGISTRY-}rabbitmqpcfweb
    build:
      context: .
      dockerfile: RabbitMqPcf.Web/RabbitMqPcf.Web/Dockerfile
    depends_on:
    - rabbitmq
    networks:
    - frontend
    - backend

  rabbitmq:
    image: rabbitmq:3.7.17
    hostname: "rabbitmq"
    ports:
    - "5672:5672"    
    - "15672:15672"
    expose:
    - "5672"
    networks:
    - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge